#!/usr/bin/env bash

# Clean up temporary installations
cleanup_temp() {
    local delete_item="$1"

    log "INFO" "Cleaning up temporary installation..."
    $DRY_RUN || rm -rf "$delete_item"
    color_echo "INFO" "Cleanup completed."
}
