#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/brew-regex"

update_rpath() {
    local python_binary="$1"
    local target_path="$2"

    
    color_echo "DEBUG" "Checking Python binary at $python_binary"

    if [[ ! -f "$python_binary" ]]; then
        log "WARN" "Error: Python binary not found at $python_binary"
        log "INFO" "Please verify the Python version and binary path."
        exit 1
    fi

    libraries=$(otool -L "$python_binary" | awk 'NR>1 {print $1}' | grep -vE "^\s*(/System|/usr/lib|$BREW_PATH_REGEX)")

    while read -r library; do
        [[ -n "$library" ]] || continue
        if [[ -f "$library" && "$library" != "$target_path"  ]]; then
            if [[ "$library" == */lib/* ]]; then
                local base_name=$(basename "$library")
                $DRY_RUN || install_name_tool -change "$library" "${target_path}/lib/${base_name}" "$python_binary"
                log "INFO" "Updated rpath: $library -> ${target_path}/lib/${base_name}"
            fi
            
        else
            log "WARN" "Warning: $library is not a valid file, skipping."
        fi
    done <<< "$libraries"
}

update_lc_rpath() {
    local python_binary="$1"
    local target_path="$2"

    color_echo "DEBUG" "Checking Python binary at $python_binary"

    if [[ ! -f "$python_binary" ]]; then
        log "WARN" "Error: Python binary not found at $python_binary"
        log "INFO" "Please verify the Python version and binary path."
        exit 1
    fi

    rpaths=$(otool -l "$python_binary" | awk '/cmd LC_RPATH/,/path/' | grep path | awk '{print $2}')

    log "INFO" "Existing LC_RPATH entries in $python_binary:"
    log "INFO" "$rpaths"

    while IFS= read -r library || [[ -n "$library" ]]; do
       
        if [[ $library == "${ARM_BREW_DIR}/lib" || $library == "${X86_BREW_DIR}/lib" ]]; then
            log "INFO" "Updating LC_RPATH: $library -> ${target_path}/deps"
            $DRY_RUN || install_name_tool -rpath "$library" "${target_path}/deps" "$python_binary"
            if [[ $? -eq 0 ]]; then
                log "INFO" "Successfully updated LC_RPATH: $library -> ${target_path}/deps"
            else
                log "WARN" "Error: Failed to update LC_RPATH for $library."
                exit 1
            fi
        elif [[ $library != "${target_path}/lib" ]]; then
            
            log "INFO" "Updating LC_RPATH: $library -> ${target_path}/lib"
            $DRY_RUN || install_name_tool -rpath "$library" "${target_path}/lib" "$python_binary"
            if [[ $? -eq 0 ]]; then
                log "INFO" "Successfully updated LC_RPATH: $library -> ${target_path}/lib"
            else
                log "WARN" "Error: Failed to update LC_RPATH for $library."
                exit 1
            fi
        else
            log "WARN" "LC_RPATH $library does not match criteria, skipping."
        fi
    done <<< "$rpaths"
}

update_fat_binary_rpath() {
    local python_binary="$1"
    local target_path="$2"
    local temp_folder="$target_path/temp"

    $DRY_RUN || mkdir -p "$temp_folder"

    $DRY_RUN || lipo -extract x86_64 "$python_binary" -output "$temp_folder/python_x86_64"
    $DRY_RUN || lipo -extract arm64 "$python_binary" -output "$temp_folder/python_arm64"

    $DRY_RUN || update_lc_rpath "$temp_folder/python_x86_64" "$target_path" 
    $DRY_RUN || update_lc_rpath "$temp_folder/python_arm64" "$target_path" 

    $DRY_RUN || lipo -create "$temp_folder/python_x86_64" "$temp_folder/python_arm64" -output "$python_binary"

    $DRY_RUN || rm -rf "$temp_folder"
    log "INFO" "Successfully updated RPATH for all architectures in $python_binary"
}


rpath_updater(){
    local python_version="$1"
    local python_path="$2"

    local target_path="$python_path"
    local minor_version=$(echo "$python_version" | cut -d. -f1,2)
    local python_binary="$python_path/bin/python${minor_version}"

    build_brew_regex

    update_rpath "$python_binary" "$target_path" 
    update_fat_binary_rpath "$python_binary" "$target_path"
}