#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/../libexec/tools/install-python-arch"


universal2_single_build() {
    local arch="$1"
    local python_version="$2"
    local custom_suffix="$3"
    local extra_params="$4"


    if [[ $arch == "x86_64" ]]; then       
        brew_path=${brew_path:-/usr/local/bin} 
    elif [[ $arch == "arm64" ]]; then
        brew_path=${brew_path:-/opt/homebrew/bin}
    else
        color_echo "ERROR" "Need --arm64 or --x86_64 for architecture"
    fi

    color_echo "INFO" "installing python $python_version $arch"
    
    if ! install_python_arch "$arch" "$python_version" "$brew_path" "$custom_suffix" "$extra_params" ; then
    color_echo "ERROR" "Error: Failed to install Python $python_version for $arch."
    exit 1
    fi
}