#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-install-python"

universal2_single_build() {
    local arch="$1"
    local python_version="$2"
    local custom_suffix="$3"
    shift 3
    local extra_params=("$@")


    if [[ $arch == "$X86_ARCH" ]]; then       
        brew_path="${X86_BREW_DIR}/bin" 
    elif [[ $arch == "$ARM_ARCH" ]]; then
        brew_path="${ARM_BREW_DIR}/bin"
    else
        color_echo "ERROR" "Need --arm64 or --x86_64 for architecture"
        exit 1
    fi

    color_echo "INFO" "installing python $python_version $arch"
    
    if ! install_python_arch "$arch" "$python_version" "$brew_path" "$custom_suffix" "${extra_params[@]}" ; then
    color_echo "ERROR" "Error: Failed to install Python $python_version for $arch."
    exit 1
    fi
}