#!/usr/bin/env bash

BREW_DUAL_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

CUSTOM_BREW_PATHS_FILE="$BREW_DUAL_ROOT/.custom_brew_paths"

add_custom_brew_path() {
    local arm_brew=""
    local x86_brew=""

    for arg in "$@"; do
        case $arg in
            arm_brew=*) arm_brew="${arg#*=}" ;;
            x86_brew=*) x86_brew="${arg#*=}" ;;
        esac
    done

    if [[ -z "$arm_brew" && -z "$x86_brew" ]]; then
        color_echo "ERROR" "Error: 'custom-brew' requires at least one of arm_brew or x86_brew paths." >&2
        color_echo "INFO" "Usage: custom-brew <arm_brew_path> <x86_brew_path>"
        exit 1
    fi

    if [[ -f "$CUSTOM_BREW_PATHS_FILE" ]]; then
        if grep -q "CUSTOM_ARM_BREW=" "$CUSTOM_BREW_PATHS_FILE"; then
            current_arm_brew=$(grep "CUSTOM_ARM_BREW=" "$CUSTOM_BREW_PATHS_FILE" | cut -d'=' -f2)
            if [[ "$current_arm_brew" != "$arm_brew" ]]; then
                sed -i '' "s|^CUSTOM_ARM_BREW=.*|CUSTOM_ARM_BREW=$arm_brew|" "$CUSTOM_BREW_PATHS_FILE"
                echo "INFO" "Updated ARM Homebrew path to: $arm_brew"
            else
                echo "INFO" "ARM Homebrew path is already set to: $arm_brew"
            fi
        else
            echo "CUSTOM_ARM_BREW=$arm_brew" >> "$CUSTOM_BREW_PATHS_FILE"
            echo "INFO" "Added ARM Homebrew path: $arm_brew"
        fi

        if grep -q "CUSTOM_X86_BREW=" "$CUSTOM_BREW_PATHS_FILE"; then
            current_x86_brew=$(grep "CUSTOM_X86_BREW=" "$CUSTOM_BREW_PATHS_FILE" | cut -d'=' -f2)
            if [[ "$current_x86_brew" != "$x86_brew" ]]; then

                sed -i '' "s|^CUSTOM_X86_BREW=.*|CUSTOM_X86_BREW=$x86_brew|" "$CUSTOM_BREW_PATHS_FILE"
                echo "INFO" "Updated x86 Homebrew path to: $x86_brew"
            else
                echo "INFO" "x86 Homebrew path is already set to: $x86_brew"
            fi
        else
            echo "CUSTOM_X86_BREW=$x86_brew" >> "$CUSTOM_BREW_PATHS_FILE"
            echo "INFO" "Added x86 Homebrew path: $x86_brew"
        fi
    else
        echo "CUSTOM_ARM_BREW=$arm_brew" > "$CUSTOM_BREW_PATHS_FILE"
        echo "CUSTOM_X86_BREW=$x86_brew" >> "$CUSTOM_BREW_PATHS_FILE"
        echo "INFO" "Created new custom brew paths file and added paths."
    fi
}
